# Iteration of array

In [ ]:
l=[10,20,30,40]

In [2]:
for i in range(len(l)):
    print(l[i])

NameError: name 'l' is not defined

In [5]:
import numpy as np
a=np.array([100,200,300,400,500,600])
a

array([100, 200, 300, 400, 500, 600])

In [4]:
for i in a:
    print(i,end=" ")

100 200 300 400 500 

In [6]:
b=a.reshape(2,3)
b

array([[100, 200, 300],
       [400, 500, 600]])

In [10]:
for i in b:
    
    for j in i:
        print(j,end=" ")
    print("newline")

100 200 300 newline
400 500 600 newline


In [11]:
c=a.reshape(2,3,1)
c

array([[[100],
        [200],
        [300]],

       [[400],
        [500],
        [600]]])

In [15]:
for i in c:
    for j in i:
        for k in j:
            print(k,end=" ")
            print("k iteration")
        print("j iteration")
    print("i iteration")

100 k iteration
j iteration
200 k iteration
j iteration
300 k iteration
j iteration
i iteration
400 k iteration
j iteration
500 k iteration
j iteration
600 k iteration
j iteration
i iteration


In [14]:
for i in np.nditer(c):
    print(i,end=" ")

100 200 300 400 500 600 

# joining of array

In [16]:
a=np.arange(1,5)
b=np.arange(11,20)
print(a,end=" ")
print(b,end=" ")

[1 2 3 4] [11 12 13 14 15 16 17 18 19] 

In [18]:
c=np.concatenate((a,b))
c

array([ 1,  2,  3,  4, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
a=np.arange(1,5)
b=np.arange(6,10)
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 6, 7, 8, 9])

In [21]:
c=a.reshape(2,2)
d=b.reshape(2,2)
print(c)
print(d)
print("------")
e=np.concatenate((c,d))
e

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
------


array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [27]:
f=a.reshape(2,1,2)
g=b.reshape(2,1,2)
print(f)
print(g)
print("---------")
h=np.concatenate((f,g))
h

[[[1 2]]

 [[3 4]]]
[[[6 7]]

 [[8 9]]]
---------


array([[[1, 2]],

       [[3, 4]],

       [[6, 7]],

       [[8, 9]]])

### Statistical and Mathematical operations of arrays

In [28]:
c

array([[1, 2],
       [3, 4]])

In [29]:
np.min(c)

1

In [30]:
np.max(c)

4

In [33]:
np.argmin(c)  # gives te index of min val of array

0

In [34]:
np.argmax(c)

3

In [35]:
c.mean()

2.5

In [36]:
np.mean(c)

2.5

In [37]:
np.median(c)

2.5

In [38]:
np.var(c)

1.25

In [39]:
np.average(c)

2.5

In [40]:
np.std(c)

1.118033988749895

In [42]:
# np.mode(c) error

In [43]:
#sum of all elements of array
np.sum(c)

10

In [44]:
c

array([[1, 2],
       [3, 4]])

In [45]:
np.sum(c,1) # 1 is access value for row, 0 is for columns

array([3, 7])

In [46]:
np.sum(c,0)

array([4, 6])

### stacking 
* arranging or organizing in an appropriate way
- horiontal stacking
- vertical stacking

In [47]:
c

array([[1, 2],
       [3, 4]])

In [52]:
np.hstack(c) # change in dimension

array([1, 2, 3, 4])

In [51]:
np.vstack((c,d)) # no change in dimension

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [53]:
np.sqrt(c) # square root of an element

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [54]:
np.exp(c)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [55]:
np.sin(c)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [56]:
np.log(c)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [59]:
np.log2(c)

array([[0.       , 1.       ],
       [1.5849625, 2.       ]])

In [60]:
np.log10(c)

array([[0.        , 0.30103   ],
       [0.47712125, 0.60205999]])

In [62]:
np.power(c,2)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [63]:
np.remainder(c,3)

array([[1, 2],
       [0, 1]], dtype=int32)

In [64]:
help(np.degrees)

Help on ufunc object:

degrees = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate arr

In [65]:
np.diff(c)

array([[1],
       [1]])

In [66]:
np.ediff1d(c) # converts array into 1-d array and 
            # calculates the consecutive difference of each element

array([1, 1, 1])

In [68]:
np.mod(c,4) # modulus of each element in the array

array([[1, 2],
       [3, 0]], dtype=int32)

In [69]:
np.multiply(c,100)

array([[100, 200],
       [300, 400]])

In [70]:
np.divide(c,2)

array([[0.5, 1. ],
       [1.5, 2. ]])

In [72]:
a=np.array([1+2j, 9+4j])
a

array([1.+2.j, 9.+4.j])

In [73]:
np.real(a)

array([1., 9.])

In [74]:
np.imag(a)

array([2., 4.])

### Ravel and Flatten
* both are used for creating duplicate array
* Ravel - any changes in duplicate reflect in original array
* Flatten - changes in duplicate have no effect on original array

In [75]:
original=np.arange(1,10)
original


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
copy = original.ravel()
copy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
copy[0]=100
copy

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [78]:
original

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [79]:
copy1=original.flatten()
copy1

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [80]:
original

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [81]:
copy1[2]=3000

In [82]:
copy1

array([ 100,    2, 3000,    4,    5,    6,    7,    8,    9])

In [83]:
original

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [84]:
type(copy)

numpy.ndarray

In [85]:
type(copy1)

numpy.ndarray

In [88]:
d=np.reciprocal(c)
d

array([[1, 0],
       [0, 0]], dtype=int32)

In [89]:
np.ceil(c)

array([[1., 2.],
       [3., 4.]])

In [91]:
np.floor(c)

array([[1., 2.],
       [3., 4.]])

In [97]:
np.math.factorial(15)

1307674368000