In [1]:
import numpy as np
np.random.randint(100)

17

In [2]:
np.random.rand()

0.19541234093806925

In [3]:
np.random.randint(100,size=(20))

array([83, 58, 70, 29, 60, 22, 55, 85, 91,  7, 98, 36, 91,  7, 12, 11, 20,
       38, 67, 65])

In [6]:
np.random.randint(100,size=(2,3))

array([[36, 41,  2],
       [86, 36,  7]])

In [5]:
np.random.randint(100,size=(2,3,4))

array([[[ 2, 35, 23, 76],
        [56, 56, 46, 75],
        [59, 19, 32, 27]],

       [[36, 26, 32, 44],
        [75, 38, 10, 21],
        [82, 17, 69, 25]]])

In [7]:
np.random.choice([20,55,22,66])

22

In [8]:
np.random.choice([33,44,55,66,77,88,99,22,11,23,43,65,76,88,12,87,77],size=(3,2))

array([[43, 88],
       [33, 76],
       [55, 65]])

In [9]:
np.random.choice([33,44,55,66,77,88,99,22,11,23,43,65,76,88,12,87,77],size=(3,2,4))

array([[[88, 43, 43, 99],
        [77, 65, 77, 22]],

       [[23, 12, 11, 77],
        [23, 65, 77, 99]],

       [[11, 88, 76, 11],
        [44, 76, 11, 99]]])

In [10]:
np.random.randn(10)

array([ 0.53774968,  0.70209297, -1.23765387,  0.48942309, -0.36234263,
       -0.69227503,  0.48339385, -1.49412135, -0.06166185, -0.015103  ])

In [12]:
np.random.normal() # normal distribution

0.2782627768121682

# Array Filtering

In [14]:
a=np.array([90,89,78,57,67])
b=[False,True,False,True,True]
a[b]

array([89, 57, 67])

In [17]:
# print values which are greter than 70
b=[]
for i in a:
    if i>70:
        b.append(True)
    else:
        b.append(False)
c=a[b]
c

array([90, 89, 78])

In [19]:
d=a>70
e=a[d]
e

array([90, 89, 78])

# Pandas
* Pandas is a built in library used for analysis
* used for data manipulations, visualisations, building machine learning models
* There are two main data structures in pandas Series and DataFrame

In [2]:
import pandas as pd
pd.__version__

'1.0.1'

### pandas series
* A series is similar to a 1-D Array and contains the values of same type
* dataframe is simply a table where each column is a pandas series
* creating series
    * List
    * Tuple
    * Dictionary
    * Numpy
    * Data_Range
* series indexing

In [23]:
l=[55,3,6,77,8,33]
p=pd.Series(l)
p

0    55
1     3
2     6
3    77
4     8
5    33
dtype: int64

In [3]:
t=(23,25,34)
s=pd.Series(t)
s

0    23
1    25
2    34
dtype: int64

In [4]:
pl=pd.Series(t, index=['1','2','3'])
pl

1    23
2    25
3    34
dtype: int64

In [5]:
s.index=['0','1','2']

In [6]:
s[1]

25

In [7]:
s

0    23
1    25
2    34
dtype: int64

In [8]:
s[1:3]

1    25
2    34
dtype: int64

In [9]:
s[1:4:2]

1    25
dtype: int64

In [10]:
s

0    23
1    25
2    34
dtype: int64

In [11]:
s.index=[20,21,22]

In [12]:
s

20    23
21    25
22    34
dtype: int64

In [16]:
import numpy as np
s.index=np.arange(30,33)
s

30    23
31    25
32    34
dtype: int64

In [17]:
s=pd.Series(np.square(np.arange(1,10)))
s

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
dtype: int32

In [18]:
s=pd.Series(np.square(np.arange(1,10)))
s.index=[1,2,3,4,5,6,7,8,9]
s

1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int32

In [19]:
s=pd.Series(np.square(np.arange(1,10)))
s.index=range(1,10)
s

1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int32

In [20]:
## Date Range Method

dates=pd.date_range(start="2020-10-5",end="2020-10-12")
dates

DatetimeIndex(['2020-10-05', '2020-10-06', '2020-10-07', '2020-10-08',
               '2020-10-09', '2020-10-10', '2020-10-11', '2020-10-12'],
              dtype='datetime64[ns]', freq='D')

In [21]:
help(pd.date_range)

Help on function date_range in module pandas.core.indexes.datetimes:

date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize=False, name=None, closed=None, **kwargs) -> pandas.core.indexes.datetimes.DatetimeIndex
    Return a fixed frequency DatetimeIndex.
    
    Parameters
    ----------
    start : str or datetime-like, optional
        Left bound for generating dates.
    end : str or datetime-like, optional
        Right bound for generating dates.
    periods : int, optional
        Number of periods to generate.
    freq : str or DateOffset, default 'D'
        Frequency strings can have multiples, e.g. '5H'. See
        :ref:`here <timeseries.offset_aliases>` for a list of
        frequency aliases.
    tz : str or tzinfo, optional
        Time zone name for returning localized DatetimeIndex, for example
        'Asia/Hong_Kong'. By default, the resulting DatetimeIndex is
        timezone-naive.
    normalize : bool, default False
        Normalize start/

In [22]:
### Creating Series by using numpy array

n=np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
s2=pd.Series(n,index=np.arange(20,30))
s2

20    0
21    1
22    2
23    3
24    4
25    5
26    6
27    7
28    8
29    9
dtype: int32

In [25]:
n1=np.array([23,67,8,8,30])
n1

array([23, 67,  8,  8, 30])